"use client";
import { useEffect, useMemo, useState } from 'react';

const tabs=['Overview','Store','Orders','Marketplace','Users','KYC','Subscriptions','Discounts','Storage','Audit'];
type StoreData={categories:any[]};
type OrderData={orders:any[]};

export default function Admin(){
  const [tab,setTab]=useState('Overview');
  const [data,setData]=useState<any>(null);
  const [store,setStore]=useState<StoreData>({categories:[]});
  const [orders,setOrders]=useState<OrderData>({orders:[]});
  const [code,setCode]=useState(''); const [security,setSecurity]=useState('');
  const [refresh,setRefresh]=useState(0);
  const [newCategory,setNewCategory]=useState({name:'',slug:'',description:'',imageUrl:''});

  useEffect(()=>{fetch('/api/admin/overview').then(r=>r.json()).then(setData).catch(()=>setData({error:'Admin API unavailable'}))},[refresh]);
  useEffect(()=>{if(tab==='Store') fetch('/api/admin/store').then(r=>r.json()).then(d=>setStore(d)).catch(()=>setStore({categories:[]})); if(tab==='Orders') fetch('/api/admin/store/orders').then(r=>r.json()).then(d=>setOrders(d)).catch(()=>setOrders({orders:[]}));},[tab,refresh]);

  async function request2fa(){const r=await fetch('/api/admin/2fa/request',{method:'POST'});const d=await r.json();setSecurity(d.message||d.error||'');}
  async function verify2fa(){const r=await fetch('/api/admin/2fa/verify',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({code})});const d=await r.json();setSecurity(d.ok?'Admin 2FA verified.':(d.error||'Verification failed.')); if(d.ok) setRefresh(x=>x+1);}
  async function createCategory(){const r=await fetch('/api/admin/store',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({kind:'category',...newCategory,sortOrder:store.categories.length+1})});const d=await r.json();if(!r.ok){setSecurity(d.error||'Could not create category.');return;}setNewCategory({name:'',slug:'',description:'',imageUrl:''});setRefresh(x=>x+1);}
  async function updateOrder(id:string,status:string){const r=await fetch('/api/admin/store/orders',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({id,status})});const d=await r.json();if(!r.ok){setSecurity(d.error||'Could not update order.');return;}setRefresh(x=>x+1);}
  async function sendToWaliya(id:string){const r=await fetch('/api/admin/store/waliya',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({orderId:id})});const d=await r.json();setSecurity(r.ok?'Sent to Waliya.':(d.error||'Could not send to Waliya.'));setRefresh(x=>x+1);}
  async function checkWaliya(id:string){const r=await fetch(`/api/admin/store/waliya?orderId=${id}`);const d=await r.json();setSecurity(r.ok?`Waliya status: ${d.result?.status||'not found yet'}`:(d.error||'Could not check status.'));setRefresh(x=>x+1);}
  async function linkWaliya(pkgId:string){const topUpId=prompt('Waliya topUpId:');if(topUpId==null)return;const serviceId=prompt('Waliya serviceId:');if(serviceId==null)return;const r=await fetch('/api/admin/store',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({kind:'package',id:pkgId,waliyaTopUpId:topUpId,waliyaServiceId:serviceId})});const d=await r.json();setSecurity(r.ok?'Package linked to Waliya.':(d.error||'Could not link package.'));setRefresh(x=>x+1);}
  const storeProducts=useMemo(()=>store.categories.flatMap(c=>(c.products||[]).map((p:any)=>({...p,categoryName:c.name}))),[store]);
  const allPackages=useMemo(()=>storeProducts.flatMap((p:any)=>(p.packages||[]).map((pkg:any)=>({...pkg,productName:p.name}))),[storeProducts]);

  return <div className="page"><div className="container">
    <div className="hero compact-hero"><div className="eyebrow">ZTN Official Admin</div><h1>Control center</h1><p>Server-side authorization and mandatory Admin 2FA protect this area.</p><div className="actions"><button className="btn" onClick={request2fa}>Send Admin code</button><input value={code} onChange={(e:any)=>setCode(e.target.value)} placeholder="6-digit code" inputMode="numeric" maxLength={6} style={{maxWidth:150,border:'1px solid var(--line)',borderRadius:10,padding:'10px'}}/><button className="btn btn-primary" onClick={verify2fa}>Verify</button></div>{security&&<p className={security.includes('verified')?'success':'muted'}>{security}</p>}</div>
    <div className="admin-grid"><div className="card admin-nav">{tabs.map(x=><button className={tab===x?'active':''} onClick={()=>setTab(x)} key={x}>{x}</button>)}</div><div className="card card-pad">
      {tab==='Overview' && <><h2>Overview</h2><div className="stat-grid">{['Users','Orders','Listings','Revenue'].map((x,i)=><div className="card stat" key={x}><span className="muted">{x}</span><strong>{data?.stats?.[i]??'—'}</strong></div>)}</div><div className="section"><div className="notice">Official Store products, packages, category images, availability and prices are Admin-editable. Existing paid orders retain their stored price.</div></div></>}

      {tab==='Store' && <><h2>Official Store</h2><p className="muted">Manage categories here first; product/package editing uses the same protected API and can be expanded without rebuilding the customer frontend.</p><div className="card card-pad" style={{marginBottom:14}}><h3>Add category</h3><div className="grid-2"><div className="field"><label>Name</label><input value={newCategory.name} onChange={(e:any)=>setNewCategory({...newCategory,name:e.target.value})}/></div><div className="field"><label>Slug</label><input value={newCategory.slug} onChange={(e:any)=>setNewCategory({...newCategory,slug:e.target.value})}/></div><div className="field"><label>Description</label><input value={newCategory.description} onChange={(e:any)=>setNewCategory({...newCategory,description:e.target.value})}/></div><div className="field"><label>Image URL</label><input value={newCategory.imageUrl} onChange={(e:any)=>setNewCategory({...newCategory,imageUrl:e.target.value})}/></div></div><button className="btn btn-primary" onClick={createCategory}>Add category</button></div><div className="table-wrap"><table className="table"><thead><tr><th>Category</th><th>Products</th><th>Status</th></tr></thead><tbody>{store.categories.map(c=><tr key={c.id}><td><strong>{c.name}</strong><div className="muted">/{c.slug}</div></td><td>{(c.products||[]).length}</td><td>{c.active?'Active':'Hidden'}</td></tr>)}{store.categories.length===0&&<tr><td colSpan={3} className="muted">Run Admin 2FA and reload to view Store data.</td></tr>}</tbody></table></div><div className="section"><h3>Products</h3><div className="table-wrap"><table className="table"><thead><tr><th>Product</th><th>Category</th><th>Packages</th><th>Image</th></tr></thead><tbody>{storeProducts.map(p=><tr key={p.id}><td>{p.name}</td><td>{p.categoryName}</td><td>{p.packages?.length||0}</td><td>{p.imageUrl||'Default'}</td></tr>)}</tbody></table></div></div><div className="section"><h3>Packages (Waliya linking)</h3><p className="muted">Link a Free Fire package to its Waliya topUpId/serviceId so "Send to Waliya" works for it.</p><div className="table-wrap"><table className="table"><thead><tr><th>Package</th><th>Product</th><th>Price</th><th>Waliya</th><th>Action</th></tr></thead><tbody>{allPackages.map((pkg:any)=><tr key={pkg.id}><td>{pkg.name}</td><td>{pkg.productName}</td><td>{pkg.price} ETB</td><td className="muted">{pkg.waliyaTopUpId?`${pkg.waliyaTopUpId} / ${pkg.waliyaServiceId}`:'Not linked'}</td><td><button className="btn btn-small" onClick={()=>linkWaliya(pkg.id)}>Link</button></td></tr>)}</tbody></table></div></div></>}

      {tab==='Orders' && <><h2>Store Orders</h2><div className="table-wrap"><table className="table"><thead><tr><th>Order</th><th>Customer</th><th>Product</th><th>Price</th><th>Status</th><th>Action</th><th>Waliya</th></tr></thead><tbody>{orders.orders.map(o=><tr key={o.id}><td>{o.orderNumber}</td><td>{o.user?.displayName||o.user?.email}</td><td>{o.product?.name}<div className="muted">{o.packageName}</div></td><td>{o.price} ETB</td><td>{o.status}</td><td><select value={o.status} onChange={(e:any)=>updateOrder(o.id,e.target.value)}>{['PENDING_PAYMENT','PAYMENT_SUBMITTED','PAYMENT_VERIFIED','PROCESSING','COMPLETED','CANCELLED','FLAGGED','REFUND_PENDING','REFUND_SENT'].map(s=><option key={s}>{s}</option>)}</select></td><td>{o.deliveryProvider==='WALIYA' && !o.supplierOrderRef && <button className="btn btn-small" onClick={()=>sendToWaliya(o.id)}>Send to Waliya</button>}{o.supplierOrderRef && <button className="btn btn-small" onClick={()=>checkWaliya(o.id)}>Check status ({o.supplierStatus||'PENDING'})</button>}</td></tr>)}{orders.orders.length===0&&<tr><td colSpan={7} className="muted">No orders or Admin 2FA is not verified.</td></tr>}</tbody></table></div></>}

      {!['Overview','Store','Orders'].includes(tab) && <><h2>{tab}</h2><p className="muted">This area is protected and backed by the production data model. The next Admin UI layer can expose the corresponding server endpoints without changing customer-facing flows.</p><div className="notice">Server-side authorization and audit logging are required for Admin actions.</div></>}
    </div></div>
  </div></div>;
}
