import Link from "next/link";
import { AdminShell } from "./shell";
import { prisma } from "@/lib/prisma";
import { FulfillWaliyaButton, CompleteManualButton, CheckWaliyaStatusButton, MarkPayoutPaidButton } from "./admin-actions";

function Empty({ children = "No records yet." }: { children?: React.ReactNode }) { return <div className="card empty-state"><h3>{children}</h3><p>Nothing has been recorded in Neon yet.</p></div>; }
const status=(s:string)=><span className="status available">{s}</span>;

export async function AdminOverviewLive(){
  const [users,sellers,products,orders,paid,kyc,payouts,revenue]=await Promise.all([
    prisma.user.count(), prisma.sellerProfile.count({where:{verified:true}}), prisma.product.count({where:{status:"ACTIVE"}}), prisma.order.count(), prisma.order.count({where:{status:{in:["PAID","FULFILLING","COMPLETED"]}}}), prisma.user.count({where:{kycStatus:"IN_REVIEW"}}), prisma.payout.count({where:{status:{in:["HOLD","ELIGIBLE"]}}}), prisma.order.aggregate({where:{status:{in:["PAID","FULFILLING","COMPLETED"]}},_sum:{total:true}}),
  ]);
  const recent=await prisma.order.findMany({take:8,orderBy:{createdAt:'desc'},include:{items:{include:{product:true}},payment:true}});
  return <AdminShell><div className="eyebrow">Overview</div><h1 style={{fontSize:54,marginTop:7}}>Control <span style={{color:'var(--blue)'}}>center.</span></h1><div className="admin-stats section">{[["Users",users],["Active sellers",sellers],["Live listings",products],["Orders",orders],["Paid/complete",paid],["KYC in review",kyc],["Payouts pending",payouts],["Recorded revenue",`${Number(revenue._sum.total??0).toFixed(2)} ETB`]].map(([l,v])=><div className="stat-card" key={String(l)}><div className="stat-label">{l}</div><div className="stat-value">{v}</div></div>)}</div><div className="section card"><div className="section-head"><div><div className="eyebrow">Recent orders</div><h3>Latest activity</h3></div><Link className="btn btn--ghost" href="/admin/orders">All orders</Link></div>{recent.length?<div className="table-wrap"><table><thead><tr><th>Order</th><th>Product</th><th>Amount</th><th>Payment</th><th>Status</th></tr></thead><tbody>{recent.map(o=><tr key={o.id}><td>{o.id}</td><td>{o.items.map(i=>i.product.title).join(', ')}</td><td>{Number(o.total).toFixed(2)} ETB</td><td>{o.payment?.status??'PENDING'}</td><td>{status(o.status)}</td></tr>)}</tbody></table></div>:<Empty>No orders yet.</Empty>}</div></AdminShell>;
}

export async function AdminOrdersLive(){const rows=await prisma.order.findMany({orderBy:{createdAt:'desc'},take:100,include:{buyer:true,items:{include:{product:true,seller:{include:{user:true}}}},payment:true,payout:true}});return <AdminShell><div className="eyebrow">Orders</div><h2 style={{marginTop:7}}>Order operations.</h2><p>Database-backed marketplace orders only.</p>{rows.length?<div className="table-wrap section"><table><thead><tr><th>Order</th><th>Buyer</th><th>Product</th><th>Amount</th><th>Payment</th><th>Order</th><th>Payout</th></tr></thead><tbody>{rows.map(o=><tr key={o.id}><td>{o.id}</td><td>{o.buyer?.email??'Guest'}</td><td>{o.items.map(i=>i.product.title).join(', ')}</td><td>{Number(o.total).toFixed(2)} ETB</td><td>{status(o.payment?.status??'PENDING')}</td><td>{status(o.status)}</td><td>{status(o.payout?.status??'—')}</td></tr>)}</tbody></table></div>:<Empty/>}</AdminShell>}

export async function AdminSellersLive(){const rows=await prisma.sellerProfile.findMany({orderBy:{createdAt:'desc'},take:100,include:{user:true,_count:{select:{products:true}}}});return <AdminShell><div className="eyebrow">Sellers</div><h2 style={{marginTop:7}}>Seller directory.</h2>{rows.length?<div className="table-wrap section"><table><thead><tr><th>Seller</th><th>Listings</th><th>Sales</th><th>Rating</th><th>KYC</th><th>Badge</th></tr></thead><tbody>{rows.map(s=><tr key={s.id}><td>{s.user.name||s.user.email||s.id}</td><td>{s._count.products}</td><td>{s.totalSales}</td><td>{Number(s.rating).toFixed(1)}</td><td>{status(s.user.kycStatus)}</td><td>{s.badge}</td></tr>)}</tbody></table></div>:<Empty/>}</AdminShell>}

export async function AdminProductsLive(){const rows=await prisma.product.findMany({orderBy:{createdAt:'desc'},take:100,include:{seller:{include:{user:true}}}});return <AdminShell><div className="eyebrow">Products</div><h2 style={{marginTop:7}}>Listing control.</h2>{rows.length?<div className="table-wrap section"><table><thead><tr><th>Product</th><th>Category</th><th>Seller</th><th>Price</th><th>Status</th><th>Created</th></tr></thead><tbody>{rows.map(p=><tr key={p.id}><td>{p.title}</td><td>{p.category}</td><td>{p.seller.user.name||p.seller.user.email}</td><td>{Number(p.price).toFixed(2)} ETB</td><td>{status(p.status)}</td><td>{new Date(p.createdAt).toLocaleDateString()}</td></tr>)}</tbody></table></div>:<Empty/>}</AdminShell>}

export async function AdminUsersLive(){const rows=await prisma.user.findMany({orderBy:{createdAt:'desc'},take:100,include:{_count:{select:{buyerOrders:true,products:true}}}});return <AdminShell><div className="eyebrow">Users</div><h2 style={{marginTop:7}}>User management.</h2>{rows.length?<div className="table-wrap section"><table><thead><tr><th>User</th><th>Role</th><th>KYC</th><th>Orders</th><th>Listings</th><th>Joined</th></tr></thead><tbody>{rows.map(u=><tr key={u.id}><td>{u.name||u.email||u.id}</td><td>{u.role}</td><td>{status(u.kycStatus)}</td><td>{u._count.buyerOrders}</td><td>{u._count.products}</td><td>{new Date(u.createdAt).toLocaleDateString()}</td></tr>)}</tbody></table></div>:<Empty/>}</AdminShell>}

export async function AdminPaymentsLive(){const rows=await prisma.payment.findMany({orderBy:{createdAt:'desc'},take:100});return <AdminShell><div className="eyebrow">Payments</div><h2 style={{marginTop:7}}>Payment control.</h2>{rows.length?<div className="table-wrap section"><table><thead><tr><th>Payment</th><th>Provider</th><th>Amount</th><th>Status</th><th>Reference</th><th>Created</th></tr></thead><tbody>{rows.map(p=><tr key={p.id}><td>{p.id}</td><td>{p.provider}</td><td>{Number(p.amount).toFixed(2)} ETB</td><td>{status(p.status)}</td><td>{p.providerRef??'—'}</td><td>{new Date(p.createdAt).toLocaleDateString()}</td></tr>)}</tbody></table></div>:<Empty/>}</AdminShell>}

export async function AdminPayoutsLive(){const rows=await prisma.payout.findMany({orderBy:{createdAt:'desc'},take:100,include:{seller:{include:{user:true}},order:true}});return <AdminShell><div className="eyebrow">Payouts</div><h2 style={{marginTop:7}}>Payout eligibility.</h2><p>Marketplace commission is 5%. The seller hold is 24 hours and completion is required before release.</p>{rows.length?<div className="table-wrap section"><table><thead><tr><th>Seller</th><th>Order</th><th>Seller net</th><th>Status</th><th>Eligible at</th><th>Action</th></tr></thead><tbody>{rows.map(p=><tr key={p.id}><td>{p.seller.user.name||p.seller.user.email}</td><td>{p.orderId}</td><td>{Number(p.amount).toFixed(2)} ETB</td><td>{status(p.status)}</td><td>{p.eligibleAt?new Date(p.eligibleAt).toLocaleString():'After completion + 24h'}</td><td>{p.status==='ELIGIBLE'?<MarkPayoutPaidButton id={p.id}/>:''}</td></tr>)}</tbody></table></div>:<Empty/>}</AdminShell>}

export async function AdminStoreLive(){const rows=await prisma.storeOrder.findMany({orderBy:{createdAt:'desc'},take:100,include:{buyer:true,payment:true}});return <AdminShell><div className="eyebrow">Official Store</div><h2 style={{marginTop:7}}>Provider orders.</h2><p>Free Fire uses Waliya after verified payment. Instagram orders are manually fulfilled.</p>{rows.length?<div className="table-wrap section"><table><thead><tr><th>Order</th><th>Kind</th><th>Target</th><th>Amount</th><th>Payment</th><th>Status</th><th>Action</th></tr></thead><tbody>{rows.map(o=><tr key={o.id}><td>{o.id}</td><td>{o.kind}</td><td>{o.target}</td><td>{Number(o.amount).toFixed(2)} ETB</td><td>{status(o.payment?.status??'PENDING')}</td><td>{status(o.status)}</td><td>{o.kind==='FREE_FIRE'&&o.status==='PAID'?<FulfillWaliyaButton id={o.id} failedBefore={Boolean((o.providerPayload as any)?.error)} />:o.kind==='FREE_FIRE'&&o.status==='FULFILLING'?<CheckWaliyaStatusButton id={o.id}/>:o.kind!=='FREE_FIRE'&&o.status==='MANUAL_REVIEW'?<CompleteManualButton id={o.id}/>:o.providerRef??'—'}</td></tr>)}</tbody></table></div>:<Empty/>}</AdminShell>}

export async function AdminKycLive(){const rows=await prisma.kycVerification.findMany({orderBy:{createdAt:'desc'},take:100,include:{user:true}});return <AdminShell><div className="eyebrow">KYC</div><h2 style={{marginTop:7}}>Verification queue.</h2>{rows.length?<div className="table-wrap section"><table><thead><tr><th>User</th><th>Provider</th><th>Status</th><th>Decision</th><th>Created</th></tr></thead><tbody>{rows.map(k=><tr key={k.id}><td>{k.user.name||k.user.email}</td><td>{k.provider}</td><td>{status(k.status)}</td><td>{k.decision??'—'}</td><td>{new Date(k.createdAt).toLocaleDateString()}</td></tr>)}</tbody></table></div>:<Empty/>}</AdminShell>}

export async function AdminDisputesLive(){const rows=await prisma.order.findMany({where:{status:'DISPUTED'},orderBy:{updatedAt:'desc'},take:100,include:{buyer:true}});return <AdminShell><div className="eyebrow">Disputes</div><h2 style={{marginTop:7}}>Problem resolution.</h2>{rows.length?<div className="table-wrap section"><table><thead><tr><th>Order</th><th>Buyer</th><th>Reported</th><th>Status</th></tr></thead><tbody>{rows.map(o=><tr key={o.id}><td>{o.id}</td><td>{o.buyer?.email??'Guest'}</td><td>{o.problemReportedAt?new Date(o.problemReportedAt).toLocaleString():'—'}</td><td>{status(o.status)}</td></tr>)}</tbody></table></div>:<Empty>No disputes.</Empty>}</AdminShell>}

export async function AdminAnalyticsLive(){const [revenue,orders,sellers]=await Promise.all([prisma.order.aggregate({where:{status:{in:['PAID','FULFILLING','COMPLETED']}},_sum:{total:true}}),prisma.order.count(),prisma.sellerProfile.count({where:{verified:true}})]);return <AdminShell><div className="eyebrow">Analytics</div><h2 style={{marginTop:7}}>Recorded metrics.</h2><div className="grid-3 section"><div className="stat-card"><div className="stat-label">Revenue recorded</div><div className="stat-value">{Number(revenue._sum.total??0).toFixed(2)} ETB</div></div><div className="stat-card"><div className="stat-label">Orders</div><div className="stat-value">{orders}</div></div><div className="stat-card"><div className="stat-label">Verified sellers</div><div className="stat-value">{sellers}</div></div></div></AdminShell>}

export async function AdminSettingsLive(){return <AdminShell><div className="eyebrow">Settings</div><h2 style={{marginTop:7}}>System configuration.</h2><div className="grid-2 section"><div className="card"><h3>Providers</h3><p>Secrets remain in environment variables. Runtime status is intentionally not fabricated when credentials are missing.</p><div className="benefit-list" style={{gridTemplateColumns:'1fr'}}>{['Clerk','Neon','Veritas','Didit','Waliya','Brevo','Cloudflare R2'].map(x=><div className="benefit" key={x}>{x}</div>)}</div></div><div className="card"><h3>Business rules</h3><div className="benefit-list" style={{gridTemplateColumns:'1fr'}}><div className="benefit">Marketplace commission: 5%</div><div className="benefit">Seller payout hold: 24 hours after completion</div><div className="benefit">Minimum payout: 100 ETB</div></div></div></div></AdminShell>}

export async function AdminAuditLive(){const rows=await prisma.auditLog.findMany({orderBy:{createdAt:'desc'},take:100,include:{actor:true}});return <AdminShell><div className="eyebrow">Audit Logs</div><h2 style={{marginTop:7}}>Recorded admin actions.</h2>{rows.length?<div className="table-wrap section"><table><thead><tr><th>Time</th><th>Admin</th><th>Action</th><th>Target</th></tr></thead><tbody>{rows.map(a=><tr key={a.id}><td>{new Date(a.createdAt).toLocaleString()}</td><td>{a.actor?.email??a.actor?.name??'System'}</td><td>{a.action}</td><td>{a.targetType}:{a.targetId??'—'}</td></tr>)}</tbody></table></div>:<Empty>No audit events yet.</Empty>}</AdminShell>}
