"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { SiteShell } from "./shell";
import { Brand } from "./brand";
import { Benefits, PremiumPlanGrid } from "./page-blocks";
import { ProductCard } from "./product-card";
import { officialStore } from "@/lib/data";
import { TierBadge, VerifiedLine } from "./badges";
import { Icons } from "./icons";
import type { ProductView } from "@/lib/marketplace";

function ErrorBox({ message }: { message: string }) { return <div className="notice" style={{marginTop:12}}>{message}</div>; }

export function SellerScreen({ sellerId }: { sellerId?: string }) {
  const [data,setData]=useState<any>(null); const [sellers,setSellers]=useState<any[]>([]); const [sales,setSales]=useState<any[]>([]); const [saleError,setSaleError]=useState(''); const [error,setError]=useState('');
  useEffect(()=>{
    const url=sellerId?`/api/sellers/${encodeURIComponent(sellerId)}`:'/api/sellers';
    fetch(url).then(async r=>{const j=await r.json();if(!r.ok)throw new Error(j.error);if(sellerId)setData(j.seller);else setSellers(j.sellers||[]);}).catch(e=>setError(e.message));
  },[sellerId]);
  useEffect(()=>{fetch('/api/seller/orders').then(async r=>{const j=await r.json();if(r.ok)setSales(j.orders||[]);}).catch(e=>setSaleError(e.message));},[]);
  async function markDelivered(id:string){setSaleError('');const r=await fetch(`/api/seller/orders/${encodeURIComponent(id)}/deliver`,{method:'POST'});const j=await r.json();if(!r.ok){setSaleError(j.error||'Unable to mark delivered');return;}setSales(current=>current.map(o=>o.id===id?{...o,deliveredAt:new Date().toISOString()}:o));}
  return <SiteShell><div className="page">{error&&<ErrorBox message={error}/>} {sellerId ? (data ? <><div className="card"><div className="profile-head"><div className="profile-avatar">{data.name.slice(0,2).toUpperCase()}</div><div><div className="profile-name"><h1 style={{fontSize:30}}>{data.name}</h1>{data.badge&&data.badge!=="NONE"?<TierBadge tier={String(data.badge).replace('PREMIUM_PLUS','Premium+').replace('PREMIUM','Premium').replace('OFFICIAL','Official').replace('TOP_SELLER','Top Seller') as any}/>:null}</div>{data.verified&&<VerifiedLine/>}<div className="muted" style={{marginTop:8}}>★ {Number(data.rating||0).toFixed(1)}</div></div></div><p style={{marginTop:16}}>{data.bio||'This seller has not added a bio yet.'}</p></div><div className="section"><div className="eyebrow">Listings</div><h2>Active products.</h2><div className="product-grid">{data.listings.map((p:any)=><ProductCard key={p.id} product={p}/>)}{!data.listings.length&&<div className="card empty-state"><h3>No active listings.</h3><p>This seller has no active products right now.</p></div>}</div></div></> : !error ? <div className="card empty-state"><h3>Loading seller profile…</h3></div> : null) : <><div className="eyebrow">Seller directory</div><h1 style={{marginTop:10}}>Verified sellers.</h1><p>Seller profiles and listing counts come directly from Neon. No invented metrics.</p><div className="section grid-4">{sellers.map(s=><Link key={s.id} href={`/seller?seller=${encodeURIComponent(s.id)}`} className="card"><div className="profile-head" style={{gridTemplateColumns:'auto 1fr'}}><div className="profile-avatar" style={{width:64,height:64,borderRadius:20,fontSize:20}}>{s.name.slice(0,2).toUpperCase()}</div><div><div className="profile-name"><strong>{s.name}</strong>{s.badge&&s.badge!=="NONE"?<TierBadge tier={String(s.badge).replace('PREMIUM_PLUS','Premium+').replace('PREMIUM','Premium').replace('OFFICIAL','Official').replace('TOP_SELLER','Top Seller') as any}/>:null}</div>{s.verified&&<VerifiedLine/>}<div className="muted" style={{fontSize:12,marginTop:6}}>★ {Number(s.rating||0).toFixed(1)} · {s.listings} active listings</div></div></div></Link>)}{!sellers.length&&<div className="card empty-state"><h3>No verified sellers yet.</h3><p>Verified sellers will appear here after they publish listings.</p></div>}</div></>}
  {sales.length>0&&<div className="section"><div className="eyebrow">Your sales</div><h2>Recent sales.</h2>{saleError&&<ErrorBox message={saleError}/>}<div className="table-wrap"><table><thead><tr><th>Order</th><th>Item</th><th>Status</th><th>Delivered</th><th>Action</th></tr></thead><tbody>{sales.map((sale:any)=><tr key={sale.id}><td>{sale.id}</td><td>{sale.items.map((item:any)=>item.title).join(', ')}</td><td>{sale.status}</td><td>{sale.deliveredAt?new Date(sale.deliveredAt).toLocaleString():'Not delivered'}</td><td>{sale.status==='PAID'&&!sale.deliveredAt&&!sale.hasCredentials?<button className="btn btn--soft" onClick={()=>markDelivered(sale.id)}>Mark delivered</button>:'—'}</td></tr>)}</tbody></table></div></div>}
  </div></SiteShell>;
}

export function SellScreen() {
  const [files,setFiles]=useState<File[]>([]); const [form,setForm]=useState({title:"",category:"Gaming Accounts",price:"",level:"",uid:"",region:"",email:"",password:"",description:""}); const [busy,setBusy]=useState(false); const [message,setMessage]=useState("");
  const update=(k:string,v:string)=>setForm(f=>({...f,[k]:v}));
  async function publish(){
    setBusy(true); setMessage("");
    try{
      const imageKeys:string[]=[];
      for(const file of files){
        const u=await fetch('/api/uploads',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({contentType:file.type,size:file.size})});
        const uj=await u.json(); if(!u.ok) throw new Error(uj.error||'Upload failed');
        const up=await fetch(uj.url,{method:'PUT',headers:{'content-type':file.type,'content-length':String(file.size)},body:file}); if(!up.ok) throw new Error('Image upload failed');
        imageKeys.push(uj.key);
      }
      const r=await fetch('/api/listings',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({...form,price:Number(form.price),level:form.level?Number(form.level):undefined,images:imageKeys})});
      const j=await r.json(); if(!r.ok) throw new Error(j.error||'Publish failed');
      setMessage(`Listing published: ${j.product.title}`); setForm({title:"",category:"Gaming Accounts",price:"",level:"",uid:"",region:"",email:"",password:"",description:""}); setFiles([]);
    }catch(e){setMessage(e instanceof Error?e.message:'Publish failed');}finally{setBusy(false);}
  }
  return <SiteShell><div className="page"><div className="eyebrow">Seller</div><h1 style={{marginTop:12}}>Create a listing.</h1><p>KYC is required before publishing. Photos go to Cloudflare R2 through a server-issued upload URL.</p>{message&&<ErrorBox message={message}/>}<div className="sell-layout section"><div className="card"><div className="upload-box"><input type="file" accept="image/jpeg,image/png,image/webp" multiple onChange={e=>setFiles(Array.from(e.target.files??[]).slice(0,3))}/><div style={{textAlign:"center",marginTop:10}}><h3>{files.length ? `${files.length} photo${files.length>1?'s':''} selected` : 'Add product photos'}</h3><p style={{fontSize:12}}>Up to 3 photos · max 10 MB each</p></div></div><div className="form-grid two" style={{marginTop:18}}><div className="field"><label>Title</label><input value={form.title} onChange={e=>update('title',e.target.value)} placeholder="Your listing title"/></div><div className="field"><label>Category</label><select value={form.category} onChange={e=>update('category',e.target.value)}><option>Gaming Accounts</option><option>Gaming Top-Up</option><option>Design & Graphics</option><option>Free Fire Sensitivity</option></select></div><div className="field"><label>Price (ETB)</label><input value={form.price} onChange={e=>update('price',e.target.value)} type="number" min="0.01" step="0.01"/></div><div className="field"><label>Level</label><input value={form.level} onChange={e=>update('level',e.target.value)} type="number"/></div><div className="field"><label>UID</label><input value={form.uid} onChange={e=>update('uid',e.target.value)}/></div><div className="field"><label>Region</label><input value={form.region} onChange={e=>update('region',e.target.value)}/></div></div><div className="form-grid" style={{marginTop:14}}><div className="field"><label>Email</label><input value={form.email} onChange={e=>update('email',e.target.value)}/></div><div className="field"><label>Password</label><input value={form.password} onChange={e=>update('password',e.target.value)} type="password"/></div><div className="field"><label>Description</label><textarea value={form.description} onChange={e=>update('description',e.target.value)}/></div></div><button disabled={busy} className="btn btn--primary" style={{width:'100%',marginTop:18}} onClick={publish}>{busy?'Publishing…':'Publish Listing'}</button></div><div className="card"><div className="eyebrow">Rules</div><h3>Protected seller flow.</h3><div className="benefit-list" style={{gridTemplateColumns:'1fr'}}><div className="benefit">✓ KYC required before publish.</div><div className="benefit">✓ Server validates the seller and price.</div><div className="benefit">✓ Account credentials are encrypted at rest.</div><div className="benefit">✓ Upload links are scoped to your Clerk user and expire.</div></div></div></div></div></SiteShell>;
}

export function StoreScreen() { return <SiteShell><div className="page"><div className="eyebrow">Official Store</div><h1 style={{marginTop:12}}>Games + <span style={{color:'var(--blue)'}}>Social.</span></h1><p>Waliya supplies the catalog. ZTN exposes only currently available services.</p><div className="section grid-2">{[["Games","Free Fire is the currently available game service.","/official-store/games"],["Social","Instagram Followers and Instagram Likes are available.","/official-store/social"]].map(([title,desc,href])=><Link href={href} className="card" key={title}><div className="category-icon"><Icons.Gamepad2/></div><h2 style={{marginTop:14}}>{title}</h2><p>{desc}</p><span className="status available" style={{width:'fit-content'}}>Available now</span></Link>)}</div></div></SiteShell>; }

export function GamesScreen() { return <SiteShell><div className="page"><div className="eyebrow">Official Store / Games</div><h1 style={{marginTop:12}}>Free Fire.</h1><p>Other game availability follows the live Waliya catalog and is not shown as purchasable until active.</p><Link href="/official-store/free-fire" className="card" style={{display:'block',marginTop:24}}><div style={{display:'flex',gap:16,alignItems:'center'}}><img src="/assets/free-fire.svg" alt="" width={96} height={78}/><div><h3>Free Fire</h3><p>Top Up · Membership · Booyah Pass</p><span className="status available">Available</span></div></div></Link></div></SiteShell>; }

export function FreeFireScreen() {
  const [catalog,setCatalog]=useState<any[]>([]); const [selected,setSelected]=useState<any>(null); const [uid,setUid]=useState(''); const [zoneName,setZoneName]=useState('MENA / ME'); const [confirm,setConfirm]=useState(false); const [error,setError]=useState(''); const [loading,setLoading]=useState(false);
  useEffect(()=>{fetch('/api/store/catalog').then(async r=>{const j=await r.json();if(!r.ok) throw new Error(j.error);setCatalog(j.catalog??[])}).catch(e=>setError(e.message));},[]);
  async function create(){
    setLoading(true);setError('');
    try{const r=await fetch('/api/store/orders',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({kind:'FREE_FIRE',topUpId:selected.productId,serviceId:selected.serviceId,uid,zoneName})});const j=await r.json();if(!r.ok)throw new Error(j.error);const p=await fetch('/api/payments/create',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({storeOrderId:j.order.id,checkoutToken:j.order.checkoutToken})});const pj=await p.json();if(!p.ok)throw new Error(pj.error);location.href=pj.checkoutUrl;}catch(e){setError(e instanceof Error?e.message:'Checkout failed');}finally{setLoading(false);}
  }
  const serviceOptions=catalog.flatMap((p:any)=>p.services.map((s:any)=>({...s,productId:p.id,productName:p.name}))).filter((s:any)=>s.etbPrice!=null);
  return <SiteShell><div className="page"><div className="eyebrow">Official Store / Games / Free Fire</div><div className="store-hero" style={{marginTop:16}}><div className="store-preview"><img src="/assets/free-fire.svg" alt=""/><div className="store-preview__copy"><div className="status available">Available</div><h1 style={{fontSize:54}}>Free Fire</h1><p>Waliya-powered service catalog. Price is read from the provider and converted to ETB, then +5 ETB ZTN markup.</p></div></div><div className="card"><div className="form-grid"><div className="field"><label>UID</label><input value={uid} onChange={e=>setUid(e.target.value)} placeholder="Enter Free Fire UID" inputMode="numeric"/></div><div className="field"><label>Region / Zone</label><input value={zoneName} onChange={e=>setZoneName(e.target.value)}/></div><div className="field"><label>Waliya service</label><select value={selected?`${selected.productId}|${selected.id}`:''} onChange={e=>{const [p,s]=e.target.value.split('|').map(Number);setSelected(serviceOptions.find(x=>x.productId===p&&x.id===s)||null)}}><option value="">Choose an active service</option>{serviceOptions.map((s:any)=><option key={`${s.productId}-${s.id}`} value={`${s.productId}|${s.id}`}>{s.productName} · {s.name} — {s.etbPrice.toFixed(2)} ETB</option>)}</select></div></div>{error&&<ErrorBox message={error}/>}<button disabled={!uid||!selected||loading} className="btn btn--primary" style={{width:'100%',marginTop:16}} onClick={()=>setConfirm(true)}>Continue</button><p className="helper">ZTN does not call a separate UID validation API. You confirm the UID before payment.</p></div></div>{confirm&&<div className="modal-backdrop" onClick={()=>setConfirm(false)}><div className="modal-card" onClick={e=>e.stopPropagation()}><div className="eyebrow">Confirm details</div><h3 style={{marginTop:8}}>Confirm your Free Fire UID</h3><div className="card" style={{marginTop:14,boxShadow:'none'}}><div className="product-meta"><span>UID</span><strong>{uid}</strong></div><div className="product-meta"><span>Service</span><strong>{selected?.name}</strong></div><div className="product-meta"><span>Price</span><strong>{selected?.etbPrice?.toFixed(2)} ETB</strong></div></div><div style={{display:'flex',gap:8,marginTop:16}}><button className="btn btn--ghost" onClick={()=>setConfirm(false)} style={{flex:1}}>Edit</button><button disabled={loading} className="btn btn--primary" onClick={create} style={{flex:1}}>{loading?'Opening…':'Confirm & Pay'}</button></div></div></div>}</div></SiteShell>;
}

export function SocialScreen() { return <SiteShell><div className="page"><div className="eyebrow">Official Store / Social</div><h1 style={{marginTop:12}}>Instagram services.</h1><p>Currently available social products are limited to Followers and Likes.</p><div className="grid-2 section">{officialStore.social.map(item=><Link key={item.name} href={item.href} className="card"><img src={item.image} alt="" style={{width:'100%',borderRadius:18,aspectRatio:'1.5/1',objectFit:'cover'}}/><div style={{marginTop:14}}><span className="status available">Available</span><h3 style={{marginTop:10}}>{item.name}</h3><p style={{fontSize:12}}>{item.subtitle}</p></div></Link>)}</div></div></SiteShell>; }

export function InstagramScreen() {
  const [followersTarget,setFollowersTarget]=useState(''); const [likesTarget,setLikesTarget]=useState(''); const [followers,setFollowers]=useState('1000'); const [likes,setLikes]=useState('1000'); const [busy,setBusy]=useState(false); const [error,setError]=useState('');
  const followQty=Math.min(5000,Math.max(100,Math.floor((Number(followers)||100)/100)*100)); const followDiscount=Math.min(Math.floor(followQty/100)*0.01,0.5); const followPrice=Math.round(followQty*0.89*(1-followDiscount)*100)/100; const likeQty=Math.min(10000,Math.max(100,Math.floor((Number(likes)||100)/100)*100)); const likeDiscount=Math.min(Math.floor(likeQty/100)*0.01,0.5); const likePrice=Math.round(likeQty*0.44*(1-likeDiscount)*100)/100;
  async function buy(kind:string,quantity:number){setBusy(true);setError('');try{const r=await fetch('/api/store/orders',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({kind,target:kind==='INSTAGRAM_FOLLOWERS'?followersTarget:likesTarget,quantity})});const j=await r.json();if(!r.ok)throw new Error(j.error);const p=await fetch('/api/payments/create',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({storeOrderId:j.order.id,checkoutToken:j.order.checkoutToken})});const pj=await p.json();if(!p.ok)throw new Error(pj.error);location.href=pj.checkoutUrl;}catch(e){setError(e instanceof Error?e.message:'Checkout failed')}finally{setBusy(false)}}
  return <SiteShell><div className="page"><div className="eyebrow">Official Store / Social / Instagram</div><h1 style={{marginTop:12}}>Instagram <span style={{color:'var(--blue)'}}>services.</span></h1>{error&&<ErrorBox message={error}/>}<div className="grid-2 section"><div className="card"><div className="category-icon"><Icons.Sparkles/></div><h2 style={{marginTop:12}}>Followers</h2><p>0.89 ETB each. The discount increases 1% for every 100 followers, capped at 50%. Maximum quantity: 5,000.</p><div className="form-grid"><div className="field"><label>Username / profile link</label><input value={followersTarget} onChange={e=>setFollowersTarget(e.target.value)} placeholder="@yourusername"/></div><div className="field"><label>Quantity</label><input type="number" min="100" max="5000" step="100" value={followers} onChange={e=>setFollowers(e.target.value)}/></div></div><div className="product-price" style={{marginTop:12}}><strong>{followPrice.toFixed(2)}</strong><span>ETB</span></div><button disabled={busy||!followersTarget} className="btn btn--primary" style={{marginTop:16,width:'100%'}} onClick={()=>buy('INSTAGRAM_FOLLOWERS',followQty)}>Buy Followers</button></div><div className="card"><div className="category-icon"><Icons.Sparkles/></div><h2 style={{marginTop:12}}>Likes</h2><p>0.44 ETB each. Quantity must be in steps of 100.</p><div className="form-grid"><div className="field"><label>Post / Reel link</label><input value={likesTarget} onChange={e=>setLikesTarget(e.target.value)} placeholder="https://instagram.com/p/..."/></div><div className="field"><label>Quantity</label><input type="number" min="100" step="100" value={likes} onChange={e=>setLikes(e.target.value)}/></div></div><div className="product-price" style={{marginTop:12}}><strong>{likePrice.toFixed(2)}</strong><span>ETB</span></div><button disabled={busy||!likesTarget} className="btn btn--primary" style={{marginTop:16,width:'100%'}} onClick={()=>buy('INSTAGRAM_LIKES',likeQty)}>Buy Likes</button></div></div><div className="card"><strong>Delivery</strong><p>Instagram orders are manually fulfilled by Admin after verified payment. The buyer sees the order status in Orders.</p></div></div></SiteShell>;
}

export function PremiumScreen({plus=false}:{plus?:boolean}) {
  const [busy,setBusy]=useState(false); const [error,setError]=useState(""); const [selected,setSelected]=useState<{tier:string;days:number;price:number}|null>(null);
  const plans=plus?[[7,299],[30,499],[90,999],[180,1599],[365,2699]]:[[7,99],[30,299],[90,799],[180,1399],[365,2499]];
  async function buy(){if(!selected)return;setBusy(true);setError("");try{const r=await fetch('/api/subscriptions/purchase',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({tier:plus?'PREMIUM_PLUS':'PREMIUM',days:selected.days})});const j=await r.json();if(!r.ok)throw new Error(j.error);const p=await fetch('/api/payments/create',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({storeOrderId:j.order.id,checkoutToken:j.order.checkoutToken})});const pj=await p.json();if(!p.ok)throw new Error(pj.error);location.href=pj.checkoutUrl;}catch(e){setError(e instanceof Error?e.message:'Unable to start payment')}finally{setBusy(false)}}
  return <SiteShell><div className="page"><div className="eyebrow">Membership</div><h1 style={{marginTop:12}}>{plus?'Premium+':'Premium'}</h1><p>{plus?'Everything in Premium, with larger limits and deeper seller tooling.':'A polished upgrade for sellers who want more room and more visibility.'}</p><Benefits plus={plus}/>{error&&<ErrorBox message={error}/>}<div className="section"><div className="section-head"><div><div className="eyebrow">Plans</div><h2>Choose duration.</h2></div></div><div className="plan-grid">{plans.map(([days,price],i)=><button key={days} className={`plan-card ${plus?'plus':''}`} onClick={()=>setSelected({tier:plus?'PREMIUM_PLUS':'PREMIUM',days,price})}><div className="eyebrow">{days===7?'7 days':days===30?'1 month':days===90?'3 months':days===180?'6 months':'12 months'}</div><h3>{price} ETB</h3><span className="muted">KYC required</span></button>)}</div>{selected&&<div className="card" style={{marginTop:16}}><div className="eyebrow">Confirm plan</div><h3 style={{marginTop:6}}>{plus?'Premium+':'Premium'} · {selected.days} days · {selected.price} ETB</h3><p>Payment is created from the selected plan on the server. You must have verified KYC.</p><button disabled={busy} className="btn btn--primary" onClick={buy}>{busy?'Opening payment…':'Confirm & Pay'}</button></div>}</div><div className="card section"><div className="eyebrow">Current plan</div><p>Your active plan and expiration are loaded from Neon after payment verification.</p></div></div></SiteShell>; }

export function ProfileScreen() {
  const [data,setData]=useState<any>(null); const [error,setError]=useState('');
  useEffect(()=>{fetch('/api/me').then(async r=>{const j=await r.json();if(!r.ok)throw new Error(j.error);setData(j)}).catch(e=>setError(e.message));},[]);
  return <SiteShell><div className="page">{error&&<ErrorBox message={error}/>}<div className="card"><div className="profile-head"><div className="profile-avatar">{data?.user?.name?.slice(0,2).toUpperCase()||'ZT'}</div><div><div className="profile-name"><h2>{data?.user?.name||'Your profile'}</h2>{data?.user?.seller?.badge && data.user.seller.badge!=='NONE'?<TierBadge tier={String(data.user.seller.badge).replace('PREMIUM_PLUS','Premium+').replace('PREMIUM','Premium').replace('OFFICIAL','Official').replace('TOP_SELLER','Top Seller') as any}/>:null}</div>{data?.user?.seller?.verified&&<VerifiedLine/>}<div className="muted" style={{fontSize:13,marginTop:8}}>{data?.user?.email||'Sign in account'}</div></div><div className="profile-actions"><Link className="btn btn--ghost" href="/onboarding">Edit Profile</Link><Link className="btn btn--primary" href="/sell">Manage Listings</Link></div></div><p>{data?.user?.bio||'Complete your profile to add a bio and links.'}</p></div><div className="section"><div className="section-head"><div><div className="eyebrow">Your listings</div><h2>Active listings.</h2></div></div><div className="product-grid">{(data?.listings||[]).map((p:any)=><ProductCard key={p.id} product={{id:p.id,title:p.title,category:p.category,price:Number(p.price),seller:p.seller?.user?.name||data?.user?.name||'Seller',image:Array.isArray(p.images)&&p.images[0]?p.images[0]:'/assets/game-account.svg',verified:data?.user?.seller?.verified,level:p.level??undefined,region:p.region??undefined}}/>)}{data&&!data.listings?.length&&<div className="card empty-state"><h3>No listings yet.</h3><p>Publish your first verified listing from Sell.</p></div>}</div></div></div></SiteShell>;
}

export function PurchaseScreen() {
  const [product,setProduct]=useState<ProductView|null>(null); const [error,setError]=useState(''); const [busy,setBusy]=useState(false);
  useEffect(()=>{const id=new URLSearchParams(location.search).get('product');if(!id){setError('No product selected.');return}fetch(`/api/products/${id}`).then(async r=>{const j=await r.json();if(!r.ok)throw new Error(j.error);setProduct(j.product)}).catch(e=>setError(e.message));},[]);
  async function checkout(){if(!product)return;setBusy(true);try{const r=await fetch('/api/orders',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({productId:product.id})});const j=await r.json();if(!r.ok)throw new Error(j.error);const p=await fetch('/api/payments/create',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({orderId:j.order.id,checkoutToken:j.order.checkoutToken})});const pj=await p.json();if(!p.ok)throw new Error(pj.error);location.href=pj.checkoutUrl;}catch(e){setError(e instanceof Error?e.message:'Checkout failed')}finally{setBusy(false)}}
  return <SiteShell><div className="page"><div className="eyebrow">Checkout</div><h1 style={{marginTop:12}}>Confirm purchase.</h1>{error&&<ErrorBox message={error}/>} {product&&<div className="grid-2 section"><div className="card"><div style={{display:'flex',gap:14,alignItems:'center'}}><img src={product.image} alt="" width={110} height={90} style={{borderRadius:18,objectFit:'cover'}}/><div><h3>{product.title}</h3><div className="muted">{product.seller}{product.rating!=null?` · ★ ${product.rating.toFixed(1)}`:''}</div></div></div><div className="product-price" style={{marginTop:20}}><strong>{product.price.toFixed(2)}</strong><span>ETB</span></div></div><div className="card"><div className="eyebrow">Guest checkout</div><h3>Veritas hosted payment</h3><p>The order amount is loaded from the server database. The browser cannot choose the price.</p><div className="step"><div className="step-num">1</div><div><strong>Order created</strong><div className="muted">Unique order + payment record.</div></div></div><div className="step"><div className="step-num">2</div><div><strong>Pay securely</strong><div className="muted">Hosted by Veritas.</div></div></div><button disabled={busy} className="btn btn--primary" style={{width:'100%',marginTop:14}} onClick={checkout}>{busy?'Opening checkout…':'Continue to Payment'}</button></div></div>}</div></SiteShell>;
}

export function PaymentSuccessScreen() { return <SiteShell><div className="page" style={{display:'grid',placeItems:'center',minHeight:'70vh'}}><div className="card" style={{maxWidth:650,textAlign:'center'}}><div className="category-icon" style={{margin:'auto',width:78,height:78,borderRadius:24}}><Icons.CheckCircle2 size={38}/></div><div className="eyebrow" style={{marginTop:18}}>Payment flow</div><h1 style={{fontSize:54,marginTop:8}}>We are checking it.</h1><p>Veritas payment confirmation is processed server-side. Your order status changes only after a verified provider event.</p><Link className="btn btn--primary" href="/orders">View Orders</Link></div></div></SiteShell>; }

export function OrdersScreen() {
  const [orders,setOrders]=useState<any[]>([]); const [storeOrders,setStoreOrders]=useState<any[]>([]); const [error,setError]=useState(''); const [actionError,setActionError]=useState(''); const [credentials,setCredentials]=useState<Record<string,{email:string;password:string}>>({}); const [busy,setBusy]=useState<string|null>(null);
  useEffect(()=>{Promise.all([fetch('/api/orders').then(r=>r.json()),fetch('/api/store/orders').then(r=>r.json())]).then(([a,b])=>{if(a.ok===false&&b.ok===false)throw new Error(a.error||b.error);setOrders(a.orders||[]);setStoreOrders(b.orders||[])}).catch(e=>setError(e.message));},[]);
  async function showLoginDetails(id:string){setBusy(id);setActionError('');try{const r=await fetch(`/api/orders/${encodeURIComponent(id)}/credentials`,{cache:'no-store'});const j=await r.json();if(!r.ok)throw new Error(j.error||'Unable to load login details');setCredentials(c=>({...c,[id]:{email:j.email,password:j.password}}));setOrders(current=>current.map(o=>o.id===id?{...o,deliveredAt:o.deliveredAt||new Date().toISOString()}:o));}catch(e){setActionError(e instanceof Error?e.message:'Unable to load login details')}finally{setBusy(null)}}
  async function reportProblem(id:string){if(!window.confirm('Report a problem with this order? The payout will stay on hold.'))return;setBusy(id);setActionError('');try{const r=await fetch(`/api/orders/${encodeURIComponent(id)}/report`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({})});const j=await r.json();if(!r.ok)throw new Error(j.error||'Unable to report the order');setOrders(current=>current.map(o=>o.id===id?{...o,status:'DISPUTED'}:o));}catch(e){setActionError(e instanceof Error?e.message:'Unable to report the order')}finally{setBusy(null)}}
  return <SiteShell><div className="page"><div className="eyebrow">Orders</div><h1 style={{marginTop:12}}>Your purchases.</h1>{error&&<ErrorBox message={error}/>} {actionError&&<ErrorBox message={actionError}/>}<div className="table-wrap section"><table><thead><tr><th>Order</th><th>Product</th><th>Amount</th><th>Payment</th><th>Status</th><th>Date</th><th>Action</th></tr></thead><tbody>{orders.map((o:any)=>{const canReport=o.status==='PAID'||o.status==='FULFILLING';const canShowCredentials=(o.status==='PAID'||o.status==='FULFILLING'||o.status==='COMPLETED')&&o.payment?.status==='VERIFIED'&&o.items?.some((i:any)=>i.product?.hasCredentials);const creds=credentials[o.id];return <tr key={o.id}><td>{o.id}</td><td>{o.items?.map((i:any)=>i.product?.title).join(', ')||'Marketplace order'}</td><td>{Number(o.total).toFixed(2)} ETB</td><td>{o.payment?.status||'PENDING'}</td><td><span className="status available">{o.status}</span></td><td>{new Date(o.createdAt).toLocaleDateString()}</td><td>{canShowCredentials||canReport?<div style={{display:'grid',gap:6}}>{canShowCredentials&&!creds&&<button className="btn btn--soft" disabled={busy===o.id} onClick={()=>showLoginDetails(o.id)}>{busy===o.id?'Loading…':'Show login details'}</button>}{creds&&<div className="notice"><strong>Email:</strong> {creds.email}<br/><strong>Password:</strong> {creds.password}</div>}{canReport&&<button className="btn btn--ghost" disabled={busy===o.id} onClick={()=>reportProblem(o.id)}>Report a problem</button>}</div>:'—'}</td></tr>})}{storeOrders.map((o:any)=><tr key={`store-${o.id}`}><td>{o.id}</td><td>{o.kind.replace('INSTAGRAM_FOLLOWERS','Instagram Followers').replace('INSTAGRAM_LIKES','Instagram Likes').replace('FREE_FIRE','Free Fire')}</td><td>{Number(o.amount).toFixed(2)} ETB</td><td>{o.payment?.status||'PENDING'}</td><td><span className="status available">{o.status}</span></td><td>{new Date(o.createdAt).toLocaleDateString()}</td><td>—</td></tr>)}{!orders.length&&!storeOrders.length&&!error&&<tr><td colSpan={7}>No orders yet.</td></tr>}</tbody></table></div></div></SiteShell>;
}

export function PlanScreen() { return <SiteShell><div className="page"><div className="eyebrow">Plan</div><h1 style={{marginTop:12}}>What ZTN is building.</h1><p>Informational roadmap only. No dates or guarantees.</p><div className="section grid-3"><div className="card"><span className="status available">V1 / Now</span><h3 style={{marginTop:12}}>Marketplace</h3><p>Gaming accounts, sensitivity, gaming top-up, design & graphics, seller profiles, guest buying and hosted payments.</p></div><div className="card"><span className="status available">Next</span><h3 style={{marginTop:12}}>Discovery</h3><p>More official store categories, richer digital-product categories and better seller tooling.</p></div><div className="card"><span className="status unavailable">Future</span><h3 style={{marginTop:12}}>Expansion</h3><p>More games and social services, additional payment options and more seller automation.</p></div></div></div></SiteShell>; }

export function AuthScreen({signUp=false}:{signUp?:boolean}){return <div className="welcome"><div className="welcome__inner" style={{maxWidth:520}}><Link href="/"><Brand/></Link><div className="card" style={{marginTop:30}}><div className="eyebrow">ZTN account</div><h2 style={{marginTop:8}}>{signUp?'Create your account.':'Welcome back.'}</h2><p>Authentication is handled by Clerk in production.</p><div className="notice">Use the Clerk sign-in/sign-up page to continue. ZTN does not collect passwords in its own form.</div><Link className="btn btn--primary" style={{width:'100%',marginTop:15}} href={signUp?'/sign-up':'/sign-in'}>{signUp?'Create account':'Sign in'}</Link></div></div></div>}

export function OnboardingScreen(){const [name,setName]=useState('');const [bio,setBio]=useState('');const [msg,setMsg]=useState('');const [kyc,setKyc]=useState('');const save=async(skip=false)=>{setMsg('Saving…');const r=await fetch('/api/onboarding',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name:skip?undefined:name,bio:skip?undefined:bio})});const j=await r.json();if(!r.ok){setMsg(j.error);return}location.href='/';};const startKyc=async()=>{setKyc('Opening verification…');const r=await fetch('/api/didit/session',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({})});const j=await r.json();if(!r.ok){setKyc(j.error||'KYC unavailable');return}location.href=j.url;};return <SiteShell><div className="page" style={{maxWidth:700}}><div className="eyebrow">Profile setup</div><h1 style={{marginTop:12}}>Make your profile yours.</h1><p>One simple setup screen. You can skip and return later.</p><div className="card section"><div className="form-grid"><div className="field"><label>Name</label><input value={name} onChange={e=>setName(e.target.value)} placeholder="Your display name"/></div><div className="field"><label>Bio</label><textarea value={bio} onChange={e=>setBio(e.target.value)} placeholder="What do you sell?"/></div></div><div style={{display:'flex',gap:8,marginTop:16}}><button className="btn btn--ghost" onClick={()=>save(true)}>Skip</button><button className="btn btn--primary" onClick={()=>save(false)}>Finish</button></div>{msg&&<ErrorBox message={msg}/>}</div><div className="card section"><div className="eyebrow">Verification</div><h3 style={{marginTop:6}}>Seller and Premium access</h3><p>Complete Didit verification when you want to sell or buy Premium/Premium+.</p><button className="btn btn--soft" onClick={startKyc}>Start KYC</button>{kyc&&<ErrorBox message={kyc}/>}</div></div></SiteShell>}
