import fs from 'node:fs';
import path from 'node:path';
const root=process.cwd();
const required=['package.json','.env.example','next.config.ts','tsconfig.json','app/layout.tsx','app/page.tsx','app/store/page.tsx','app/store/[category]/page.tsx','app/store/[category]/[product]/page.tsx','app/store/order/page.tsx','app/components/order-form.tsx','app/admin/page.tsx','app/kyc/page.tsx','app/api/health/route.ts','app/api/store/orders/route.ts','app/api/kyc/start/route.ts','app/api/kyc/webhook/route.ts','prisma/schema.prisma','prisma/seed.ts','lib/security.ts','lib/b2.ts','lib/didit.ts','lib/email.ts','app/api/email/brevo/webhook/route.ts','app/api/subscriptions/purchase/route.ts','app/api/marketplace/orders/route.ts','app/api/marketplace/orders/[orderId]/route.ts','app/api/marketplace/reviews/route.ts','scripts/simulate-flows.mjs','scripts/check-ts-syntax.cjs','app/onboarding/page.tsx','app/api/onboarding/complete/route.ts','app/api/auth/google/start/route.ts','app/api/auth/google/callback/route.ts','app/u/[username]/page.tsx','app/api/marketplace/orders/auto-complete/route.ts','app/api/payments/veritas/create/route.ts','app/api/payments/veritas/confirm/route.ts','app/api/payments/veritas/webhook/route.ts'];
const missing=required.filter(x=>!fs.existsSync(path.join(root,x)));
const all=fs.readdirSync(path.join(root,'app'),{recursive:true}).filter(x=>String(x).match(/\.(ts|tsx)$/)).map(x=>path.join(root,'app',x));
const forbidden=[]; for(const f of all){const t=fs.readFileSync(f,'utf8'); if(/post creation|post expiry|createPost|Post\s+model|Feed/i.test(t)) forbidden.push(path.relative(root,f));}
const pkg=JSON.parse(fs.readFileSync(path.join(root,'package.json'),'utf8'));
const checks=[['next dependency',Boolean(pkg.dependencies?.next)],['prisma dependency',Boolean(pkg.dependencies?.['@prisma/client'])],['database model',fs.readFileSync(path.join(root,'prisma/schema.prisma'),'utf8').includes('model User')],['store models',fs.readFileSync(path.join(root,'prisma/schema.prisma'),'utf8').includes('model StoreProduct')&&fs.readFileSync(path.join(root,'prisma/schema.prisma'),'utf8').includes('model StoreOrder')],['marketplace models',fs.readFileSync(path.join(root,'prisma/schema.prisma'),'utf8').includes('model Listing')&&fs.readFileSync(path.join(root,'prisma/schema.prisma'),'utf8').includes('model MarketplaceOrder')],['kyc model',fs.readFileSync(path.join(root,'prisma/schema.prisma'),'utf8').includes('model KycSession')],['b2 adapter',fs.existsSync(path.join(root,'lib/b2.ts'))],['didit adapter',fs.existsSync(path.join(root,'lib/didit.ts'))],['brevo adapter',fs.readFileSync(path.join(root,'lib/email.ts'),'utf8').includes('api.brevo.com/v3/smtp/email')],['subscription payment model',fs.readFileSync(path.join(root,'prisma/schema.prisma'),'utf8').includes('model SubscriptionPayment')],['email delivery model',fs.readFileSync(path.join(root,'prisma/schema.prisma'),'utf8').includes('model EmailDelivery')]];
console.log('ZTN verification'); console.log('Required files:', required.length, 'Missing:', missing.length); if(missing.length) console.log('Missing:',missing); console.log('Forbidden feed/post references:',forbidden.length); if(forbidden.length) console.log(forbidden); for(const [n,ok] of checks) console.log(`${ok?'PASS':'FAIL'}  ${n}`);
if(missing.length||forbidden.length||checks.some(x=>!x[1])) process.exit(1);
console.log('PASS  source contract checks');
